apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  type: ClusterIP
  selector:
    app: ghost
  ports:
  - port: 80
    targetPort: 2368
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  serviceName: "ghost"
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        env:
          - name: database__client
            value: mysql
          - name: database__connection__database
            value: ghost
          - name: database__connection__host
            value: ghost-db-cluster-do-user-11332857-0.b.db.ondigitalocean.com
          - name: database__connection__port
            value: "25060"
          - name: database__connection__user
            valueFrom:
              secretKeyRef:
                name: ghost-database-creds
                key: username
          - name: database__connection__password
            valueFrom:
              secretKeyRef:
                name: ghost-database-creds
                key: password
          - name: url
            value: "https://blog.buddiesofbudgie.org"
        ports:
        - containerPort: 2368
        volumeMounts:
        - name: ghost
          mountPath: /var/lib/ghost/content
  volumeClaimTemplates:
  - metadata:
      name: ghost
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 5Gi
